name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make

      - name: Test application
        run: make test
        
      - name: Run Test
        run: ./test/main.c

      - name: Run Test1
        run: ./test/board_test.c


